package screenscmd

import (
	"bytes"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/meta-tui/cuppa/libs/cuppafile/disk"
	"github.com/meta-tui/cuppa/libs/document/design"
)

func saveDesign(t *testing.T, dir, name string) {
	t.Helper()
	doc := design.NewDocument(name, 40, 8)
	doc.Add(design.Node{Component: "lipgloss.label", Name: "Title", Rect: design.Rect{W: 20, H: 1},
		Props: map[string]string{"text": name}, Bind: map[string]string{"text": "Title"}, Event: "Open"})
	doc.Keys = []design.KeyBinding{{Key: "esc", Event: "Back"}}
	if _, err := disk.Save(filepath.Join(dir, strings.ToLower(name)+".cuppa"), doc); err != nil {
		t.Fatal(err)
	}
}

func TestScreensCommandWritesAFolderOfDesigns(t *testing.T) {
	designs, out := t.TempDir(), filepath.Join(t.TempDir(), "screens")
	saveDesign(t, designs, "Colours")
	saveDesign(t, designs, "Settings")

	var stdout, stderr bytes.Buffer
	if code := Run([]string{designs, "-o", out}, &stdout, &stderr); code != 0 {
		t.Fatalf("exit %d: %s", code, stderr.String())
	}
	for _, name := range []string{"colours_screen_contract.go", "settings_screen_view.go", "cuppa_runtime.go"} {
		if _, err := os.Stat(filepath.Join(out, name)); err != nil {
			t.Errorf("%s not written", name)
		}
	}
	src, _ := os.ReadFile(filepath.Join(out, "colours_screen_contract.go"))
	if !strings.Contains(string(src), "package screens") || !strings.Contains(string(src), "ColoursOpen") {
		t.Errorf("contract:\n%s", src)
	}

	// A design that is gone takes its files with it; a hand-written file in
	// the way stops the export.
	if err := os.Remove(filepath.Join(designs, "settings.cuppa")); err != nil {
		t.Fatal(err)
	}
	if code := Run([]string{designs, "-o", out}, &stdout, &stderr); code != 0 {
		t.Fatalf("second export: %s", stderr.String())
	}
	if _, err := os.Stat(filepath.Join(out, "settings_screen_view.go")); err == nil {
		t.Error("stale screen kept")
	}
	if err := os.WriteFile(filepath.Join(out, "cuppa_runtime.go"), []byte("package screens\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	stderr.Reset()
	if code := Run([]string{designs, "-o", out}, &stdout, &stderr); code != 1 || !strings.Contains(stderr.String(), "did not generate") {
		t.Errorf("hand-written file overwritten: code %d %s", code, stderr.String())
	}
}

func TestScreensCommandUsage(t *testing.T) {
	var stdout, stderr bytes.Buffer
	if code := Run(nil, &stdout, &stderr); code != 2 || !strings.Contains(stderr.String(), "usage") {
		t.Errorf("code %d %q", code, stderr.String())
	}
}

// --check writes nothing: it passes while the package is what the designs
// export and fails, listing the files, when it is not.
func TestCheckSaysWhetherThePackageIsCurrent(t *testing.T) {
	dir := t.TempDir()
	designs := filepath.Join(dir, "designs")
	if err := os.MkdirAll(designs, 0o755); err != nil {
		t.Fatal(err)
	}
	doc := design.NewDocument("Hello", 20, 3)
	doc.Add(design.Node{Component: "lipgloss.label", Name: "Title", Rect: design.Rect{W: 10, H: 1}, Props: map[string]string{"text": "Hi"}, Bind: map[string]string{"text": "Title"}})
	if _, err := disk.Save(filepath.Join(designs, "hello.cuppa"), doc); err != nil {
		t.Fatal(err)
	}
	out := filepath.Join(dir, "screens")
	var o, e bytes.Buffer
	if code := Run([]string{designs, "-o", out, "-p", "screens", "--check"}, &o, &e); code != 1 {
		t.Fatalf("an empty folder is not current: exit %d\n%s%s", code, o.String(), e.String())
	}
	if !strings.Contains(o.String(), "missing") {
		t.Errorf("missing files are not listed:\n%s", o.String())
	}
	if _, err := os.Stat(out); err == nil {
		t.Error("--check created the folder")
	}
	if code := Run([]string{designs, "-o", out, "-p", "screens"}, &o, &e); code != 0 {
		t.Fatalf("export: %d %s", code, e.String())
	}
	o.Reset()
	if code := Run([]string{designs, "-o", out, "-p", "screens", "--check"}, &o, &e); code != 0 || !strings.Contains(o.String(), "current") {
		t.Fatalf("just exported: exit %d\n%s%s", code, o.String(), e.String())
	}
	// A change of the design, and a stale generated file.
	doc.Nodes[0].Props["text"] = "Hello"
	doc.Nodes[0].Bind["text"] = "Greeting"
	if _, err := disk.Save(filepath.Join(designs, "hello.cuppa"), doc); err != nil {
		t.Fatal(err)
	}
	stale := filepath.Join(out, "old_screen_view.go")
	if err := os.WriteFile(stale, []byte("// Code generated by Cuppa. DO NOT EDIT.\n\npackage screens\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	o.Reset()
	if code := Run([]string{designs, "-o", out, "-p", "screens", "--check"}, &o, &e); code != 1 {
		t.Fatalf("a changed design: exit %d\n%s", code, o.String())
	}
	for _, want := range []string{"hello_screen_contract.go: differs", "old_screen_view.go: generated for a screen that is no longer designed"} {
		if !strings.Contains(o.String(), want) {
			t.Errorf("%q missing:\n%s", want, o.String())
		}
	}
}
