package gosource

import (
	_ "embed"
	"fmt"
	"sort"
	"strconv"
	"strings"

	"github.com/meta-tui/cuppa/libs/document/design"
)

//go:embed runtime_go.txt
var runtimeSource string

//go:embed app_go.txt
var appSource string

// generated lists the components that have real code behind them.
var generated = map[string]bool{
	"lipgloss.box": true, "lipgloss.label": true,
	"bubbles.textinput": true, "bubbles.textarea": true, "bubbles.list": true, "bubbles.table": true,
	"bubbles.viewport": true, "bubbles.paginator": true, "bubbles.spinner": true, "bubbles.progress": true,
	"bubbles.stopwatch": true, "bubbles.timer": true,
}

// Generate turns doc into a Go project. The same document always gives the
// same files.
func Generate(doc design.Document, cat Catalog) Project {
	module := Slug(doc.Name)
	p := Project{Module: module, Files: map[string]string{}}
	placed := leaves(doc, cat)
	p.Files["go.mod"] = goMod(module)
	p.Files["main.go"] = appSource
	p.Files["runtime.go"] = runtimeSource
	p.Files["layout.go"] = layoutSource(doc, placed)
	for _, l := range placed {
		if !generated[l.Kind] {
			p.Notes = append(p.Notes, fmt.Sprintf("%s (%s) is not generated yet: it is drawn as an empty frame", l.Name, l.Kind))
		}
	}
	p.Files["README.md"] = readme(doc, p.Notes)
	return p
}

// Slug turns a design name into a module name: lowercase letters, digits and
// dashes.
func Slug(name string) string {
	var b strings.Builder
	dash := false
	for _, r := range strings.ToLower(name) {
		if (r >= 'a' && r <= 'z') || (r >= '0' && r <= '9') {
			if dash && b.Len() > 0 {
				b.WriteByte('-')
			}
			dash = false
			b.WriteRune(r)
		} else {
			dash = true
		}
	}
	if b.Len() == 0 {
		return "cuppa-design"
	}
	return b.String()
}

func goMod(module string) string {
	return fmt.Sprintf("module %s\n\ngo 1.24\n\nrequire (\n\tcharm.land/bubbles/v2 %s\n\tcharm.land/bubbletea/v2 %s\n\tcharm.land/lipgloss/v2 %s\n)\n",
		module, bubblesVersion, bubbleteaVersion, lipglossVersion)
}

// layoutSource is the part that comes from the design: the canvas and where
// each component sits, with its properties.
func layoutSource(doc design.Document, placed []leaf) string {
	var b strings.Builder
	b.WriteString("package main\n\n")
	b.WriteString("// Generated by Cuppa from the design " + strconv.Quote(doc.Name) + ".\n")
	b.WriteString("// Components are listed back to front.\n\n")
	fmt.Fprintf(&b, "const (\n\tcanvasW    = %d\n\tcanvasH    = %d\n\tbackground = %s\n)\n\n", doc.Width, doc.Height, strconv.Quote(doc.Background))
	b.WriteString("var layout = []placed{\n")
	for _, l := range placed {
		fmt.Fprintf(&b, "\t{Kind: %s, Name: %s, X: %d, Y: %d, W: %d, H: %d, Props: map[string]string{", strconv.Quote(l.Kind), strconv.Quote(l.Name), l.Rect.X, l.Rect.Y, l.Rect.W, l.Rect.H)
		keys := make([]string, 0, len(l.Props))
		for k := range l.Props {
			keys = append(keys, k)
		}
		sort.Strings(keys)
		for i, k := range keys {
			if i > 0 {
				b.WriteString(", ")
			}
			fmt.Fprintf(&b, "%s: %s", strconv.Quote(k), strconv.Quote(l.Props[k]))
		}
		b.WriteString("}},\n")
	}
	b.WriteString("}\n")
	return b.String()
}

func readme(doc design.Document, notes []string) string {
	var b strings.Builder
	fmt.Fprintf(&b, "# %s\n\nA Bubble Tea v2 program generated by Cuppa.\n\n", doc.Name)
	b.WriteString("```sh\ngo mod tidy\ngo run .\n```\n\n")
	b.WriteString("Tab and Shift+Tab move between components that take input, clicks focus them, Esc quits.\n\n")
	b.WriteString("- `layout.go` is the design: where each component sits and its properties.\n")
	b.WriteString("- `runtime.go` wraps the real Bubbles models and draws boxes and labels. Change it freely.\n")
	b.WriteString("- `main.go` is the Bubble Tea model that runs them.\n")
	if len(notes) > 0 {
		b.WriteString("\n## Not generated yet\n\n")
		for _, n := range notes {
			b.WriteString("- " + n + "\n")
		}
	}
	return b.String()
}
