package gosource

import (
	_ "embed"
	"fmt"
	"go/format"
	"sort"
	"strconv"
	"strings"

	"github.com/meta-tui/cuppa/libs/catalog/definition"
	"github.com/meta-tui/cuppa/libs/document/design"
	"github.com/meta-tui/cuppa/libs/layout/expr"
)

//go:embed screens_go.txt
var screensSource string

// GeneratedHeader starts every file GenerateScreens writes. WriteScreens
// replaces only files that start with it.
const GeneratedHeader = "// Code generated by Cuppa. DO NOT EDIT."

// listKeys are the text properties that hold a list of items separated by
// commas; a bound one is a []string in the screen's contract.
var listKeys = map[string]bool{
	"items": true, "options": true, "entries": true, "tabs": true, "buttons": true,
	"columns": true, "labels": true, "headers": true, "bindings": true, "checked": true, "values": true,
}

// rowsKey is the text property that holds the rows of a table, separated by
// semicolons, with commas between cells; a bound one is a [][]string.
const rowsKey = "rows"

// input is one field of a screen's props.
type input struct {
	field, name, typ, def string
	use                   string
}

// GenerateScreens turns designs into a Go package of data-agnostic screens:
// for each design a contract (the inputs and events bound in the design), a
// view function that draws it for any values, and a handle function that turns
// clicks and keys into the contract's events. pkg is the package name. The
// package holds only generated files; see ADR 0007.
func GenerateScreens(docs []design.Document, cat Catalog, pkg string) Project {
	pkg = strings.ToLower(strings.Join(words(pkg), ""))
	if pkg == "" {
		pkg = "screens"
	}
	p := Project{Module: pkg, Files: map[string]string{}}
	used := map[string]bool{}
	files := map[string]bool{}
	needs := map[string]bool{}
	for _, doc := range docs {
		ident := pascal(doc.Name)
		if ident == "" || used[ident] {
			p.Notes = append(p.Notes, fmt.Sprintf("%q: its name gives no free identifier (%q); give the design a unique name", doc.Name, ident))
			continue
		}
		used[ident] = true
		placed := leaves(doc, cat)
		sc := buildScreen(doc, ident, placed, cat).with(pkg)
		p.Notes = append(p.Notes, sc.notes...)
		p.Files[snake(doc.Name)+"_screen_contract.go"] = tidy(sc.contract, &p)
		p.Files[snake(doc.Name)+"_screen_view.go"] = tidy(sc.view, &p)
		for _, l := range placed {
			if !generated[l.Kind] {
				p.Notes = append(p.Notes, fmt.Sprintf("%s: %s (%s) is not generated yet: it is drawn as an empty frame", doc.Name, l.Name, l.Kind))
			}
			e, ok := extensions[l.Kind]
			if !ok || files[e.file] {
				continue
			}
			files[e.file] = true
			p.Files["cuppa_"+e.file] = asPackage(e.text, pkg)
			if e.require != "" && !needs[e.require] {
				needs[e.require] = true
				p.Requires = append(p.Requires, e.require)
			}
		}
	}
	sort.Strings(p.Requires)
	p.Files["cuppa_runtime.go"] = asPackage(runtimeSource, pkg)
	p.Files["cuppa_widgets.go"] = asPackage(widgetsSource, pkg)
	p.Files["cuppa_screens.go"] = asPackage(screensSource, pkg)
	return p
}

// asPackage puts a runtime template into the screens package, marked as
// generated.
func asPackage(text, pkg string) string {
	text = strings.ReplaceAll(text, "\r\n", "\n")
	text = strings.Replace(text, "package main", "package "+pkg, 1)
	text = strings.ReplaceAll(text, "It is yours to change;\n// layout.go is the part that comes from the design.", "Cuppa writes it again on every export;\n// the screens' contract and view files are the part that comes from the designs.")
	text = strings.ReplaceAll(text, "Change them freely.", "Cuppa writes them again on every export.")
	return GeneratedHeader + "\n\n" + text
}

// tidy formats generated source; a file that does not parse is kept as it is
// and reported.
func tidy(src string, p *Project) string {
	out, err := format.Source([]byte(src))
	if err != nil {
		p.Notes = append(p.Notes, "generated code does not parse: "+err.Error())
		return src
	}
	return string(out)
}

type screen struct {
	contract, view string
	notes          []string
}

// with sets the package name in the generated source.
func (sc screen) with(pkg string) screen {
	sc.contract = strings.Replace(sc.contract, "package PKG", "package "+pkg, 1)
	sc.view = strings.Replace(sc.view, "package PKG", "package "+pkg, 1)
	return sc
}

// partSource is one component of a screen as the view needs it.
type partSource struct {
	l      leaf
	assign []string
	show   string
	// cond is the Go condition of a show-if that is an expression ("w >= 100").
	cond string
}

func buildScreen(doc design.Document, ident string, placed []leaf, cat Catalog) screen {
	var sc screen
	note := func(format string, a ...any) { sc.notes = append(sc.notes, doc.Name+": "+fmt.Sprintf(format, a...)) }

	var inputs []input
	index := map[string]int{}
	fields := map[string]string{"Theme": "the screen's theme"}
	register := func(name, typ, def, use string) (string, bool) {
		if i, ok := index[name]; ok {
			if inputs[i].typ != typ {
				note("input %q is used as %s and as %s; the second use stays as designed", name, inputs[i].typ, typ)
				return "", false
			}
			inputs[i].use += ", " + use
			return inputs[i].field, true
		}
		field := pascal(name)
		if field == "" {
			note("input %q gives no Go name", name)
			return "", false
		}
		if other, taken := fields[field]; taken {
			note("input %q gives the name %s, which is already %s", name, field, other)
			return "", false
		}
		fields[field] = "input " + strconv.Quote(name)
		index[name] = len(inputs)
		inputs = append(inputs, input{field: field, name: name, typ: typ, def: def, use: use})
		return field, true
	}

	// The palette: a typed field per named colour, in the order they were named.
	type paletteField struct{ field, name, color string }
	var palette []paletteField
	paletteOf := map[string]string{}
	for _, sw := range doc.Theme.Palette {
		field := pascal(sw.Name)
		if field == "" {
			note("colour %q gives no Go name", sw.Name)
			continue
		}
		if other, taken := paletteOf[field]; taken {
			note("colour %q gives the name %s, which colour %q already has", sw.Name, field, other)
			continue
		}
		paletteOf[field] = sw.Name
		palette = append(palette, paletteField{field: field, name: sw.Name, color: sw.Color})
	}
	paletteFieldOf := map[string]string{}
	for _, pf := range palette {
		paletteFieldOf[pf.name] = pf.field
	}

	var events []string
	eventOf := map[string]string{}
	addEvent := func(e string) {
		if _, seen := eventOf[e]; seen {
			return
		}
		name := pascal(e)
		if name == "" {
			note("event %q gives no Go name", e)
			return
		}
		eventOf[e] = name
		events = append(events, e)
	}

	// Row types: a bound Rows component is a typed list, one struct per input.
	type rowType struct {
		name, input, signature string
		fields                 []string
		colour                 []bool
	}
	var rowTypes []rowType
	rowTypeIndex := map[string]int{}
	// Hint types: a bound key bar is a typed list of keys and labels.
	type hintType struct{ name, input string }
	var hintTypes []hintType
	hintTypeIndex := map[string]bool{}

	var parts []partSource
	usesStrconv := false
	// readRefs are the inputs that conditions and layout expressions read.
	var readRefs []string
	for _, l := range placed {
		ps := partSource{l: l}
		def, _ := cat.Get(l.Kind)
		if l.Kind == rowsKind && len(palette) > 0 {
			// Columns and cells name colours (@Name); they are read through
			// the palette the program hands in.
			var args []string
			for _, pf := range palette {
				args = append(args, strconv.Quote(pf.name), "p.Palette."+pf.field, strconv.Quote(pf.color))
			}
			ps.assign = append(ps.assign, fmt.Sprintf("v[\"theme.palette\"] = paletteCode(%s)", strings.Join(args, ", ")))
		}
		for _, key := range sortedKeys(l.Swatches) {
			if field, ok := paletteFieldOf[l.Swatches[key]]; ok {
				ps.assign = append(ps.assign, fmt.Sprintf("if p.Palette.%s != \"\" {\n\t\t\t\tv[%q] = p.Palette.%s\n\t\t\t}", field, key, field))
			}
		}
		for _, key := range sortedKeys(l.Bind) {
			spec, ok := def.Prop(key)
			if !ok {
				continue
			}
			if l.Kind == colourPickerKind && key == "value" {
				// The picker is state the program owns: the input is a
				// ColourPicker, which draws itself through three properties.
				var tabs []string
				for _, t := range splitList(l.Props["tabs"], ",") {
					tabs = append(tabs, strconv.Quote(t))
				}
				slide, _ := strconv.Atoi(l.Props["slide"])
				lit := fmt.Sprintf("NewColourPicker(ColourPickerWithValue(%s), ColourPickerWithTabs(%s), ColourPickerWithTab(%s), ColourPickerWithAccent(%s)).SetSlide(%d)",
					strconv.Quote(l.Props["value"]), strings.Join(tabs, ", "), strconv.Quote(l.Props["tab"]), strconv.Quote(l.Props["color"]), slide)
				field, ok := register(l.Bind[key], "ColourPicker", lit, fmt.Sprintf("%s of %q", spec.Label, l.Name))
				if !ok {
					continue
				}
				usesStrconv = true
				ps.assign = append(ps.assign,
					fmt.Sprintf("v[\"value\"] = p.%s.Value()", field),
					fmt.Sprintf("v[\"tab\"] = p.%s.Tab()", field),
					fmt.Sprintf("v[\"slide\"] = strconv.Itoa(p.%s.Slide())", field))
				continue
			}
			if l.Kind == keybarKind && key == "hints" {
				typeName := ident + pascal(l.Bind[key]) + "Hint"
				var sample []string
				for _, h := range keybarHints(l.Props[key]) {
					sample = append(sample, "{Key: "+strconv.Quote(h[0])+", Label: "+strconv.Quote(h[1])+"}")
				}
				field, ok := register(l.Bind[key], "[]"+typeName, "[]"+typeName+"{"+strings.Join(sample, ", ")+"}", fmt.Sprintf("%s of %q", spec.Label, l.Name))
				if !ok {
					continue
				}
				if !hintTypeIndex[typeName] {
					hintTypeIndex[typeName] = true
					hintTypes = append(hintTypes, hintType{name: typeName, input: field})
				}
				ps.assign = append(ps.assign, fmt.Sprintf("{\n\t\t\t\titems := make([]string, len(p.%[1]s))\n\t\t\t\tfor i, h := range p.%[1]s {\n\t\t\t\t\titems[i] = h.Key + \":\" + h.Label\n\t\t\t\t}\n\t\t\t\tv[%[2]q] = joinList(items)\n\t\t\t}", field, key))
				continue
			}
			if l.Kind == rowsKind && key == "styles" && l.Bind[rowsKey] != "" {
				note("the styles of %q follow the Style of each row of %q; the binding of its styles is not used", l.Name, l.Bind[rowsKey])
				continue
			}
			if l.Kind == rowsKind && key == rowsKey {
				cols := rowColumns(l.Props["columns"])
				var fields []string
				var colour []bool
				taken := map[string]bool{"Style": true}
				for i, c := range cols {
					f := pascal(c.name)
					if f == "" || taken[f] {
						f = "Column" + strconv.Itoa(i+1)
					}
					taken[f] = true
					taken[f+"Style"] = true
					fields = append(fields, f)
					colour = append(colour, c.colour)
				}
				if len(fields) == 0 {
					note("the rows of %q have no columns; name them in its Columns property", l.Name)
					continue
				}
				typeName := ident + pascal(l.Bind[key]) + "Row"
				signature := strings.Join(fields, ",")
				if i, seen := rowTypeIndex[typeName]; seen && rowTypes[i].signature != signature {
					note("input %q is used by rows with different columns; the second use stays as designed", l.Bind[key])
					continue
				}
				var sample []string
				styles := splitList(l.Props["styles"], ",")
				for r, cells := range rowCells(l.Props[key]) {
					var fs []string
					for i, f := range fields {
						if i < len(cells) {
							fs = append(fs, f+": "+strconv.Quote(cells[i]))
						}
					}
					style := "normal"
					if r < len(styles) {
						style = styles[r]
					}
					fs = append(fs, "Style: "+rowStyleConst(style))
					sample = append(sample, "{"+strings.Join(fs, ", ")+"}")
				}
				field, ok := register(l.Bind[key], "[]"+typeName, "[]"+typeName+"{"+strings.Join(sample, ", ")+"}", fmt.Sprintf("%s of %q", spec.Label, l.Name))
				if !ok {
					continue
				}
				if _, seen := rowTypeIndex[typeName]; !seen {
					rowTypeIndex[typeName] = len(rowTypes)
					rowTypes = append(rowTypes, rowType{name: typeName, input: field, signature: signature, fields: fields, colour: colour})
				}
				var cells []string
				for _, f := range fields {
					cells = append(cells, "r."+f)
				}
				var cellStyleCells []string
				for _, f := range fields {
					cellStyleCells = append(cellStyleCells, "cellStyleCode(r."+f+"Style)")
				}
				ps.assign = append(ps.assign, fmt.Sprintf("{\n\t\t\t\trows := make([][]string, len(p.%[1]s))\n\t\t\t\tcellStyles := make([][]string, len(p.%[1]s))\n\t\t\t\tstyles := make([]string, len(p.%[1]s))\n\t\t\t\tfor i, r := range p.%[1]s {\n\t\t\t\t\trows[i] = []string{%[2]s}\n\t\t\t\t\tcellStyles[i] = []string{%[4]s}\n\t\t\t\t\tstyles[i] = rowStyleName(r.Style)\n\t\t\t\t}\n\t\t\t\tv[%[3]q] = joinRows(rows)\n\t\t\t\tv[\"cellstyles\"] = joinRows(cellStyles)\n\t\t\t\tv[\"styles\"] = joinList(styles)\n\t\t\t}", field, strings.Join(cells, ", "), key, strings.Join(cellStyleCells, ", ")))
				continue
			}
			typ, lit := inputType(spec, key, l.Props[key])
			field, ok := register(l.Bind[key], typ, lit, fmt.Sprintf("%s of %q", spec.Label, l.Name))
			if !ok {
				continue
			}
			switch typ {
			case "int":
				usesStrconv = true
				ps.assign = append(ps.assign, fmt.Sprintf("v[%q] = strconv.Itoa(p.%s)", key, field))
			case "float64":
				usesStrconv = true
				ps.assign = append(ps.assign, fmt.Sprintf("v[%q] = strconv.FormatFloat(p.%s, 'f', -1, 64)", key, field))
			case "bool":
				usesStrconv = true
				ps.assign = append(ps.assign, fmt.Sprintf("v[%q] = strconv.FormatBool(p.%s)", key, field))
			case "[]string":
				ps.assign = append(ps.assign, fmt.Sprintf("v[%q] = joinList(p.%s)", key, field))
			case "[][]string":
				ps.assign = append(ps.assign, fmt.Sprintf("v[%q] = joinRows(p.%s)", key, field))
			default:
				ps.assign = append(ps.assign, fmt.Sprintf("v[%q] = p.%s", key, field))
			}
		}
		if l.ShowIf != "" {
			if expr.IsCondition(l.ShowIf) {
				cond, err := expr.ParseCond(l.ShowIf)
				if err != nil {
					note("the condition of %q (%s): %v", l.Name, l.ShowIf, err)
				} else {
					ps.cond = cond.GoSource()
					readRefs = append(readRefs, cond.Refs()...)
				}
			} else if field, ok := register(l.ShowIf, "bool", "true", fmt.Sprintf("whether %q is shown", l.Name)); ok {
				ps.show = "p." + field
			}
		}
		for _, src := range []string{l.Layout.X, l.Layout.Y, l.Layout.W, l.Layout.H} {
			if src == "" {
				continue
			}
			if x, err := expr.Parse(src); err == nil {
				refs, _ := x.Refs()
				readRefs = append(readRefs, refs...)
			}
		}
		if l.Event != "" {
			addEvent(l.Event)
		}
		parts = append(parts, ps)
	}
	for _, ref := range readRefs {
		if _, known := index[ref]; known {
			continue
		}
		if _, ok := register(ref, "int", "0", "read by a layout expression or a condition"); ok {
			note("input %q is read by a condition or a layout expression and bound to no property: it is a number (0 by default)", ref)
		}
	}
	for _, k := range doc.Keys {
		addEvent(k.Event)
	}
	for _, n := range doc.Nodes {
		if (n.IsGroup() || isComposite(n, cat)) && (len(n.Bind) > 0 || n.ShowIf != "" || n.Event != "") {
			note("%s is a group or pack component: its bindings, show-if and event are not exported; set them on its parts", n.Name)
		}
	}

	// The contract.
	var c strings.Builder
	fmt.Fprintf(&c, "%s\n\npackage PKG\n\n", GeneratedHeader)
	fmt.Fprintf(&c, "// %sProps is everything the %s screen takes from the program that owns it.\n", ident, doc.Name)
	fmt.Fprintf(&c, "type %sProps struct {\n", ident)
	for _, in := range inputs {
		fmt.Fprintf(&c, "\t// %s is the %s.\n\t%s %s\n", in.field, in.use, in.field, in.typ)
	}
	if len(palette) > 0 {
		fmt.Fprintf(&c, "\t// Palette is the design's named colours; set one and every component that\n\t// uses it follows. An empty one keeps the design's colour.\n\tPalette %sPalette\n", ident)
	}
	c.WriteString("\t// Theme is the colours components follow; an empty one keeps the design's.\n\tTheme Theme\n}\n\n")
	if len(palette) > 0 {
		fmt.Fprintf(&c, "// %sPalette is a field per named colour of the design.\ntype %sPalette struct {\n", ident, ident)
		for _, pf := range palette {
			fmt.Fprintf(&c, "\t// %s is the colour named %s.\n\t%s string\n", pf.field, strconv.Quote(pf.name), pf.field)
		}
		fmt.Fprintf(&c, "}\n\n// Default%sPalette is the palette as it was designed.\nfunc Default%sPalette() %sPalette {\n\treturn %sPalette{\n", ident, ident, ident, ident)
		for _, pf := range palette {
			fmt.Fprintf(&c, "\t\t%s: %s,\n", pf.field, strconv.Quote(pf.color))
		}
		c.WriteString("\t}\n}\n\n")
	}
	for _, rt := range rowTypes {
		fmt.Fprintf(&c, "// %s is one row of %s. Style says how the row is drawn.\ntype %s struct {\n", rt.name, rt.input, rt.name)
		for i, f := range rt.fields {
			what := "a cell"
			if rt.colour[i] {
				what = "a colour"
			}
			fmt.Fprintf(&c, "\t// %s is %s.\n\t%s string\n", f, what, f)
		}
		for _, f := range rt.fields {
			fmt.Fprintf(&c, "\t// %sStyle restyles the %s cell of this row; the zero value keeps the column's style.\n\t%sStyle CellStyle\n", f, f, f)
		}
		c.WriteString("\t// Style is how the row is drawn: RowNormal, RowSelected, RowDim or RowAccent.\n\tStyle RowStyle\n}\n\n")
	}
	for _, ht := range hintTypes {
		fmt.Fprintf(&c, "// %s is one hint of the key bar %s.\ntype %s struct{ Key, Label string }\n\n", ht.name, ht.input, ht.name)
	}
	fmt.Fprintf(&c, "// Default%sProps is the screen as it was designed: each input holds the value\n// it had in the design.\nfunc Default%sProps() %sProps {\n\treturn %sProps{\n", ident, ident, ident, ident)
	for _, in := range inputs {
		fmt.Fprintf(&c, "\t\t%s: %s,\n", in.field, in.def)
	}
	if len(palette) > 0 {
		fmt.Fprintf(&c, "\t\tPalette: Default%sPalette(),\n", ident)
	}
	c.WriteString("\t}\n}\n\n")
	fmt.Fprintf(&c, "// %sEvent is what a click on a component or a key raises. The concrete types\n// are the %s... structs below.\ntype %sEvent interface{ is%sEvent() }\n\n", ident, ident, ident, ident)
	for _, e := range events {
		name := ident + eventOf[e]
		fmt.Fprintf(&c, "// %s is raised by %s. X and Y are the cell inside the component that was\n// clicked, and 0 for a key.\ntype %s struct{ X, Y int }\n\nfunc (%s) is%sEvent() {}\n\n",
			name, eventSources(e, placed, doc.Keys), name, name, ident)
	}
	fmt.Fprintf(&c, "// %sKeys are the keys of the screen, for a key bar.\nvar %sKeys = []KeyHint{\n", ident, ident)
	for _, k := range doc.Keys {
		fmt.Fprintf(&c, "\t{Key: %s, Label: %s, Event: %s},\n", strconv.Quote(k.Key), strconv.Quote(k.Label), strconv.Quote(k.Event))
	}
	c.WriteString("}\n")
	sc.contract = c.String()

	// The view.
	lower := camel(doc.Name)
	var v strings.Builder
	fmt.Fprintf(&v, "%s\n\npackage PKG\n\nimport (\n", GeneratedHeader)
	if usesStrconv {
		v.WriteString("\t\"strconv\"\n\n")
	}
	v.WriteString("\ttea \"charm.land/bubbletea/v2\"\n)\n\n")
	fmt.Fprintf(&v, "const (\n\t%sWidth      = %d\n\t%sHeight     = %d\n\t%sBackground = %s\n)\n\n", lower, doc.Width, lower, doc.Height, lower, strconv.Quote(doc.Background))
	// What expressions read: the window and the inputs that are numbers or yes/no.
	var envCases strings.Builder
	for _, in := range inputs {
		switch in.typ {
		case "int":
			fmt.Fprintf(&envCases, "\t\tcase %q:\n\t\t\treturn float64(p.%s)\n", in.name, in.field)
		case "float64":
			fmt.Fprintf(&envCases, "\t\tcase %q:\n\t\t\treturn p.%s\n", in.name, in.field)
		case "bool":
			fmt.Fprintf(&envCases, "\t\tcase %q:\n\t\t\tif p.%s {\n\t\t\t\treturn 1\n\t\t\t}\n\t\t\treturn 0\n", in.name, in.field)
		}
	}
	fmt.Fprintf(&v, "// %sEnv is what the layout expressions and conditions of the screen read.\nfunc %sEnv(p %sProps, w, h int) fitEnv {\n\t_ = p\n\treturn fitEnv{W: w, H: h, Inputs: func(name string) float64 {\n\t\tswitch name {\n%s\t\t}\n\t\treturn 0\n\t}}\n}\n\n", lower, lower, ident, envCases.String())
	fmt.Fprintf(&v, "var %sParts = []screenPart[%sProps]{\n", lower, ident)
	for _, ps := range parts {
		l := ps.l
		fmt.Fprintf(&v, "\t{\n\t\tplaced: placed{Kind: %s, Name: %s, X: %d, Y: %d, W: %d, H: %d, Props: map[string]string{%s}",
			strconv.Quote(l.Kind), strconv.Quote(l.Name), l.Rect.X, l.Rect.Y, l.Rect.W, l.Rect.H, propsSource(l.Props))
		if !l.Layout.IsZero() {
			fit := fitSource(l)
			if layoutReadsEnv(l) {
				fit = fitEnvSource(l)
			}
			fmt.Fprintf(&v, ", MinW: %d, MinH: %d, %s", max(minOf(l, cat, true), 1), max(minOf(l, cat, false), 1), fit)
		}
		v.WriteString("},\n")
		if len(l.Roles) > 0 {
			fmt.Fprintf(&v, "\t\tRoles: map[string]string{%s},\n", propsSource(l.Roles))
		}
		if l.Event != "" && eventOf[l.Event] != "" {
			fmt.Fprintf(&v, "\t\tEvent: %s,\n", strconv.Quote(l.Event))
		}
		if len(ps.assign) > 0 || ps.show != "" || ps.cond != "" {
			v.WriteString("\t\tApply: func(p " + ident + "Props, v map[string]string, w, h int) bool {\n")
			for _, a := range ps.assign {
				v.WriteString("\t\t\t" + a + "\n")
			}
			show := ps.show
			if ps.cond != "" {
				v.WriteString("\t\t\te := " + lower + "Env(p, w, h)\n")
				show = ps.cond
			}
			if show == "" {
				show = "true"
			}
			v.WriteString("\t\t\treturn " + show + "\n\t\t},\n")
		}
		v.WriteString("\t},\n")
	}
	v.WriteString("}\n\n")
	fmt.Fprintf(&v, "// %s draws the screen in an area of w by h cells for the values in p.\nfunc %s(p %sProps, w, h int) Frame {\n\treturn drawScreen(%sParts, p, p.Theme, w, h, %sBackground, %sEnv)\n}\n\n", ident, ident, ident, lower, lower, lower)
	fmt.Fprintf(&v, "// %sSize is the size of area the screen was designed for.\nfunc %sSize() (w, h int) { return %sWidth, %sHeight }\n\n", ident, ident, lower, lower)
	fmt.Fprintf(&v, "// %sLayout is the screen without its drawing: the frame has the regions of the\n// visible components, so a program can size a model of its own before it is\n// drawn into one of them.\nfunc %sLayout(p %sProps, w, h int) Frame {\n\treturn layoutScreen(%sParts, p, p.Theme, w, h, %sEnv)\n}\n\n", ident, ident, ident, lower, lower)
	fmt.Fprintf(&v, "// %sHandle turns a click or a key into the screen's event. ok is false when\n// the message raises none. f is the frame the screen last returned.\nfunc %sHandle(f Frame, msg tea.Msg) (%sEvent, bool) {\n", ident, ident, ident)
	clicks := false
	for _, ps := range parts {
		if ps.l.Event != "" && eventOf[ps.l.Event] != "" {
			clicks = true
		}
	}
	if !clicks && len(doc.Keys) == 0 {
		v.WriteString("\t_, _ = f, msg\n\treturn nil, false\n}\n")
	} else {
		v.WriteString("\tswitch m := msg.(type) {\n")
		if clicks {
			v.WriteString("\tcase tea.MouseClickMsg:\n\t\tif r, ok := f.eventAt(m.X, m.Y); ok {\n\t\t\tswitch r.Event {\n")
			for _, e := range events {
				fmt.Fprintf(&v, "\t\t\tcase %s:\n\t\t\t\treturn %s%s{X: m.X - r.X, Y: m.Y - r.Y}, true\n", strconv.Quote(e), ident, eventOf[e])
			}
			v.WriteString("\t\t\t}\n\t\t}\n")
		}
		if len(doc.Keys) > 0 {
			v.WriteString("\tcase tea.KeyPressMsg:\n\t\tswitch m.String() {\n")
			for _, k := range doc.Keys {
				fmt.Fprintf(&v, "\t\tcase %s:\n\t\t\treturn %s%s{}, true\n", strconv.Quote(k.Key), ident, eventOf[k.Event])
			}
			v.WriteString("\t\t}\n")
		}
		v.WriteString("\t}\n\t_ = f\n\treturn nil, false\n}\n")
	}
	sc.view = v.String()
	return sc
}

func inputType(spec definition.PropSpec, key, value string) (typ, lit string) {
	switch {
	case spec.Kind == definition.PropInt:
		n, err := strconv.Atoi(strings.TrimSpace(value))
		if err != nil {
			n = 0
		}
		return "int", strconv.Itoa(n)
	case spec.Kind == definition.PropFloat:
		f, err := strconv.ParseFloat(strings.TrimSpace(value), 64)
		if err != nil {
			f = 0
		}
		return "float64", strconv.FormatFloat(f, 'f', -1, 64)
	case spec.Kind == definition.PropBool:
		return "bool", strconv.FormatBool(value == "true")
	case spec.Kind == definition.PropText && listKeys[key]:
		return "[]string", stringsLiteral(splitList(value, ","))
	case spec.Kind == definition.PropText && key == rowsKey:
		var rows []string
		for _, r := range splitRaw(value, ";") {
			rows = append(rows, stringsLiteral(splitList(r, ",")))
		}
		return "[][]string", "[][]string{" + strings.Join(rows, ", ") + "}"
	}
	return "string", strconv.Quote(value)
}

func stringsLiteral(items []string) string {
	q := make([]string, len(items))
	for i, s := range items {
		q[i] = strconv.Quote(s)
	}
	return "[]string{" + strings.Join(q, ", ") + "}"
}

func sortedKeys(m map[string]string) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

func propsSource(m map[string]string) string {
	keys := sortedKeys(m)
	parts := make([]string, len(keys))
	for i, k := range keys {
		parts[i] = strconv.Quote(k) + ": " + strconv.Quote(m[k])
	}
	return strings.Join(parts, ", ")
}

// minOf is the smallest width (or height) the component allows.
func minOf(l leaf, cat Catalog, width bool) int {
	def, ok := cat.Get(l.Kind)
	if !ok {
		return 1
	}
	if width {
		return def.MinSize.W
	}
	return def.MinSize.H
}

// eventSources says in words what raises an event, for the comment.
func eventSources(event string, placed []leaf, keys []design.KeyBinding) string {
	var by []string
	for _, l := range placed {
		if l.Event == event {
			by = append(by, "a click on "+strconv.Quote(l.Name))
		}
	}
	for _, k := range keys {
		if k.Event == event {
			by = append(by, "the key "+strconv.Quote(k.Key))
		}
	}
	return strings.Join(by, " or ")
}
